### ISSUE TITLE
Organogram doesn't cope with numerical pay grades

### ISSUE THREAD

**Issue by arendon** [timgentry/organogram#16]
Hi, thank you for making this available.
Trying version 1.3 with the attached file gave me that error message:

`Error: t.localeCompare is not a function`

[test.xlsx](https://github.com/timgentry/organogram/files/4185812/test.xlsx)

**Comment by timgentry** [comment]
What browser are you using?

**Comment by timgentry** [comment]
Found it. Up until now it's only every had string pay grades, eg. "Band 8A" or "SEO".

As a user
I want the organogram to cope with numeric pay grades
So that I don't have to manually alter my source data to work around it.
